# Generated by Django 2.1.8 on 2019-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoFiles',
            fields=[
                ('name', models.CharField(max_length=255,
                                          primary_key=True,
                                          serialize=False)),
                ('filepath', models.CharField(max_length=255)),
                ('creationdatetime', models.DateTimeField()),
                ('modificationdatetime', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('archived', models.BooleanField()),
            ],
            options={
                'db_table': 'file_repo',
            },
        ),
    ]
