# Generated by Django 2.1.8 on 2019-05-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190512_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repofiles',
            old_name='creationdatetime',
            new_name='file_creation_date_time',
        ),
        migrations.RenameField(
            model_name='repofiles',
            old_name='modificationdatetime',
            new_name='file_modification_date_time',
        ),
        migrations.RenameField(
            model_name='repofiles',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='repofiles',
            old_name='filepath',
            new_name='file_path',
        ),
    ]
